
<%@ page import="java.util.List" %>
<%@ page import="javax.servlet.*" %>

<%@ page import="javax.jdo.Query" %>
<%@ page import="javax.jdo.PersistenceManager" %>
<%@ page import="com.google.appengine.api.users.User" %>
<%@ page import="com.google.appengine.api.users.UserService" %>
<%@ page import="com.google.appengine.api.users.UserServiceFactory" %>
<%@ page import="NSEC.Topic" %>
<%@ page import="NSEC.Discussion" %>
<%@ page import="NSEC.PMF" %>
<%@ page import="NSEC.URL2" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<%

// query database and find the number of recommendations.

Long id=Long.parseLong(request.getParameter("id"));

// access datastore

PersistenceManager pm = PMF.get().getPersistenceManager();
		
URL2 u  = pm.getObjectById(URL2.class, id);
int rating=u.getRating();
pm.close();

//int rec=Integer.parseInt(request.getParameter("rec")); // will be generated by this page




%>


<form name="f" action="/insertRating.jsp" >

<input type="hidden" name="id" value="<%=id%>"  />
			
<input type="submit" value="recommend(<%= rating %> people)" />

</html>